package by.tr.likeitnetwork.controller.constant;


public enum CommandType {
    CHANGE_LOCALE,
    GO_TO_SIGN_IN,
    GO_TO_SIGN_UP,
    SIGN_IN,
    SIGN_UP,
    GO_TO_MAIN_PAGE,
    GO_TO_PROFILE,
    GO_TO_ERROR_PAGE,
    EXIT,
    CHANGE_PASSWORD,
    ADD_TOPIC,
    DELETE_TOPIC,
    GO_TO_TOPIC_PAGE,
    RATE_MESSAGE,
    ADD_MESSAGE,
    DELETE_MESSAGE,
    CHANGE_PROFILE_INFO,
    GO_TO_ADMIN_PAGE,
    BAN_UNBAN,
    CHANGE_ROLE,
    SHOW_HIDE_THEME,
    CHANGE_THEMES,
    GO_TO_PROFILE_SETTINGS
}
